name: Build project and run tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        go: [ 1.23.x, 1.24.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: ./go.sum
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build
      - name: Test
        run: go test .

